### ISSUE TITLE
Precompiled release?

### ISSUE THREAD

**Issue by cyaoeu** [axilesoft/IM-for-UE5#1]
The plugin doesn't build for me with 5.0.2 (errors in PmxMaterialImport.cpp:

Error	C2039	'GetEditorOnlyData': is not a member of 'UMaterial'
Error	C2660	'UPmxMaterialImport::CreateAndLinkExpressionForMaterialProperty': function does not take 6 arguments	
Error	C2039	'EditorOnly': is not a member of 'FStaticParameterSet'		
)

so it would be nice if there was a precompiled version in github releases. Not sure if this fork was meant for others or just yourself but I was looking for a VMD importer for UE5 and this looked interesting!

**Comment by axilesoft** [comment]
The code was for the main branch of UE5, and I haven't checked the latest version.

**Comment by cyaoeu** [comment]
No problem! Feel free to close this issue if this fork wasn't meant for widespread use.

**Comment by axilesoft** [comment]
dll for 5.2
