### ISSUE TITLE
Issue with VMD Importing and Animation Sequence. (Legs won't move)

### ISSUE THREAD

**Issue by masonintokyo** [axilesoft/IM-for-UE5#9]
Hello,

I successfully imported a VMD file, but I encountered an issue with the animation sequence. Specifically, the leg movements do not appear to be functioning correctly. I've verified that both the model (PMX) and the motion (VMD) work as expected in other software, such as Blender, suggesting that the files themselves are not at fault.

Could you please confirm if this behavior is expected, or if there might be a potential issue that needs addressing?

Thank you for your assistance.

Best regards,

**Comment by shimizu-izumi** [comment]
You need to convert the VMD from LegIK to LegD using this [tool](https://github.com/axilesoft/IM-for-UE5/releases/tag/vmd_tool_v0.1) as Unreals animations don't support it according to @axilesoft. I'm not sure but activating the IKRig plugin (if it's not active by default) might do something.

**Comment by masonintokyo** [comment]
thank you
